---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  # https://lyz-code.github.io/yamlfix/editor_integration/
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.17.0
    hooks:
      - id: yamlfix

  # after things that change file formatting
  # https://blog.42mate.com/installing-and-using-pre-commit-with-ansible-lint/
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.5.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        entry: ./.pre-commit-run.sh ansible-lint
        verbose: true
        args: [-p, --nocolor, -c, .ansible-lint.yml]
