---
- name: Playbook to install/configure newsscribe cluster servers
  hosts: all
  vars_files:
   - es-vars.yml # NOTE! overrides vars from es-inventory.yml

  # **** NOTE! *****
  # If you add tasks to this file, also add to
  # molecule/default/converge.yml!!!

  pre_tasks:
   - name: Include tasks/all
     ansible.builtin.include_tasks:
       file: "tasks/all.yml"
