---
# include_tasks file included by all.yml
- name: create-motd | Create file
  ansible.builtin.copy:
    dest: /etc/motd
    mode: '0644'
    owner: root
    group: root
    content: |-
      ********************************************************************
      * Media Cloud NewsScribe Elasticsearch server (not for other use!) *
      *              This cluster configured using ansible!              *
      *           (Please do not tweak this server by hand!!!)           *
      ********************************************************************
