---
# include_tasks file (included from all.yml)

# NOTE! Installing other tools from the system-dev-ops repo
# (nginx-agent statsd-proxy) are 99% identical but not worth
# making an argument taking role to do the work unless/until a playbook
# to re-create the web server (web-search, rss-fetcher, grafana)
# is desired.
- name: install-statsd-agent | Install packages for server monitoring agent
  ansible.builtin.apt:
    pkg:
      - git
      - make
      - python3-pip
      - python3.12-venv
      # please add new packages above
      # in alphabetical order to avoid dups!
    state: latest
    update_cache: true

# NOTE! command failure(s) not detected!!!
# should re-write using ansible to do as much as possible!
# ie; ansible.builtin.git??
- name: install-statsd-agent | Install server monitoring agent
  ansible.builtin.command:
    cmd: /bin/sh
    stdin: |
      cd /tmp
      rm -rf system-dev-ops
      git clone https://github.com/mediacloud/system-dev-ops
      cd system-dev-ops/monitoring/statsd-agent
      make install
      cd /tmp
      rm -rf system-dev-ops
    creates: /opt/MC/statsd-agent/statsd-agent.py
