---
# include_task file to remove /usr/lib/sysctl.d/elasticsearch.conf
# on Ubuntu 24.04 if it would lower the system default limit
# (in /etc/sysctl.d/10-map-count.conf).  Must be run after ES install!
# No doubt this could be done "more cleanly" using pure ansible,
# but just trying to get the job done, so using awk:
- name: vm_max_map_count | Install packages for vm_max_map_count check
  ansible.builtin.apt:
    pkg:
      - gawk  # needed for test in docker container
# needs shell for wildcard and ||
- name: vm_max_map_count | Check /etc/sysctl.d/*.conf
  ansible.builtin.shell: |
    awk -F= 'BEGIN { n=0 }
    $1 == "vm.max_map_count" { n=$2 }
    END { print n }' /etc/sysctl.d/*.conf || echo 0
  changed_when: false  # "never changes", for idempotency testing
  register: system
# needs shell for ||
- name: vm_max_map_count | Check /usr/lib/sysctl.d/elasticsearch.conf
  ansible.builtin.shell: |
    awk -F= 'BEGIN { n=0 }
    $1 == "vm.max_map_count" { n=$2 }
    END { print n }' /usr/lib/sysctl.d/elasticsearch.conf || echo 0
  changed_when: false  # "never changes", for idempotency testing
  register: elastic
- name: vm_max_map_count | Remove ES supplied /usr/lib/sysctl.d/elasticsearch.conf
  ansible.builtin.file:
    path: /usr/lib/sysctl.d/elasticsearch.conf
    state: absent
  when: (system.stdout | int) >= (elastic.stdout | int)
  register: es_conf_removed
# NOTE! may effect host system (but initial boot probably already did!)
- name: vm_max_map_count | Restart systemd-sysctl.service
  ansible.builtin.systemd:
    name: systemd-sysctl.service
    state: restarted
  when: es_conf_removed.changed
  tags: [skip_ansible_lint]
