---
# include_task file to remove /usr/lib/sysctl.d/elasticsearch.conf
# on Ubuntu 24.04 if it would lower the system default limit
# (in /etc/sysctl.d/10-map-count.conf)

# No doubt this could be done "more cleanly" using pure ansible,
# but just trying to get the job done, so using awk

- name: Install packages for vm_max_map_count check
  ansible.builtin.apt:
    pkg:
      - gawk # needed for test in docker container

- name: Check /etc/sysctl.d/*.conf
  shell: awk -F= 'BEGIN { n=0 } $1 == "vm.max_map_count" { n=$2; exit } END { print n }' /etc/sysctl.d/*.conf || echo 0
  changed_when: false # "never changes", for idempotency testing
  register: system

- name: Check /usr/lib/sysctl.d/elasticsearch.conf
  shell: awk -F= 'BEGIN { n=0 } $1 == "vm.max_map_count" { n=$2; exit } END { print n }' /usr/lib/sysctl.d/elasticsearch.conf || echo 0
  changed_when: false  # "never changes", for idempotency testing
  register: elastic

- name: Remove ES supplied /usr/lib/sysctl.d/elasticsearch.conf
  file:
    path: /usr/lib/sysctl.d/elasticsearch.conf
    state: absent
  when: (system.stdout | int) >= (elastic.stdout | int)
