---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Include top level es-vars.yml
      ansible.builtin.include_vars:
        file: "../../es-vars.yml"

    # after es-vars to allow override
    - name: Include vars.yml
      ansible.builtin.include_vars:
        file: "vars.yml"

    - name: Install packages
      ansible.builtin.apt:
        pkg:
        - git
        - gpg
        - unzip

    - name: Create directories necessary for installs
      ansible.builtin.command:
        cmd: "mkdir -p /usr/share/man/man1"

    - name: Run ansible-elasticsearch role
      include_role:
        name: "{{ mc_tmp }}"
