---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"

  tasks:
    - name: Include vars.yml
      ansible.builtin.include_vars:
        file: vars.yml

    # if needed, create Dockerfile from a Dockerfile.j2 template,
    # and build docker image

    - name: Create docker network
      docker_network:
        name: "{{ mc_network_name }}"
        state: present

    # https://github.com/ansible/molecule/issues/1159#issuecomment-371758925
    # has example docker_container taking data from platforms dict list
    # also baking image

    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
    - name: Create docker containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        hostname: "{{ item.name }}"
        image: "{{ mc_image }}"
        privileged: true # for systemd
        cgroupns_mode: host # for systemd [*]
        state: started
        recreate: false
        command: "{{ mc_image_command }}"
        log_driver: json-file
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:rw" # for systemd
          # _COULD_ mount a per-server /data volume
          # w/ local directory based on item.name to persist data
        networks:
          - name: "{{ mc_network_name }}"
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0 # run concurrently

    # [*] https://www.jeffgeerling.com/blog/2022/docker-and-systemd-getting-rid-dreaded-failed-connect-bus-error
    # (also requires dbus to be installed)

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: docker_jobs
      until: docker_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"
