---
driver:
  name: docker

# UGH! Force addrs, so containers easily accessible outside docker
# see also mc_ipv4_subnet in vars.yml
# (trying {{mc_ipv4_prefix}}.n below failed)

# ALSO: names also in mc_es_seed_hosts in vars.yml
# WISH: generate mc_es_seed_hosts using a property added below!!
platforms:
  - name: es-test-1
    pre_build_image: true
  - name: es-test-2
    pre_build_image: true
  - name: es-test-3
    pre_build_image: true
  - name: es-test-4
    pre_build_image: true
