---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"

  # create Dockerfile from a Dockerfile.j2 template,
  # and build docker image?
  tasks:
    - name: Include es-vars.yml
      ansible.builtin.include_vars:
        file: ../../es-vars.yml
    - name: Include vars.yml
      ansible.builtin.include_vars:
        file: vars.yml
    - name: Clone/update mediacloud/ansible-elasticsearch
      ansible.builtin.git:
        # running as root, so fetch via http (no need to tag/push)
        repo: https://github.com/{{ mc_es_ansible_elasticsearch_repo }}.git
        dest: '{{ mc_es_ansible_elasticsearch }}'
        force: '{{ mc_es_ansible_elasticsearch_force_checkout_cleanup }}'
        update: '{{ mc_es_ansible_elasticsearch_force_checkout_cleanup }}'
