---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"

  # create Dockerfile from Dockerfile.j2?
  # build docker image?
  tasks:
    - name: Include vars.yml
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Clone mediacloud/ansible-elasticsearch
      ansible.builtin.git:
        repo: "https://github.com/mediacloud/ansible-elasticsearch.git"
        dest: "{{ mc_tmp }}"
        force: true
