---
# included by different molecule phase playbooks for common variables

# PLEASE KEEP IN SORTED ORDER!

es_heap_size: 1g

################ mc_es_xxx: override defaults

mc_es_cluster_name: test_cluster

# force cluster initialization!
mc_es_initialize: true

mc_es_network_host: 0.0.0.0

mc_es_reindex_whitelist: []

# NOTE: must match entries in molecule.yml "platforms" dict
# WISH: assemble using a property in "platforms" entries
mc_es_seed_hosts:
  - es-test-1
  - es-test-2
  - es-test-3

# uncomment for debugging (avoid pushing to ansible-elasticsearch repo):
#mc_es_ansible_elasticsearch_force_checkout_cleanup: false

################ settings used in molecule files (maybe use mc_mol_XXX?)

# "A minimal systemd enabled Ubuntu 24.04 image for testing Ansible
# roles with Molecule
#
# NOTE: This image does NOT contain Ansible tooling, e.g. ansible-core
# or yamllint. Thus, the use case is as target host for Ansible
# controllers or within the Molecule create/converge/test cycle."
#
# https://github.com/trfore/docker-ubuntu2404-systemd
# https://hub.docker.com/r/trfore/docker-ubuntu2404-systemd
mc_image: trfore/docker-ubuntu2404-systemd

#mc_image_command: "sh -c \"while true; do sleep 10000; done\""
mc_image_command: "/usr/sbin/init" # symlink to systemd

# ansible network to connect containers:
mc_network_name: newsscribe-molecule-test # used in create, destroy

# PLEASE KEEP IN SORTED ORDER!
